version: "3.3"
services:
  selenium-chrome:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
  flanco:
    build: .
    depends_on:
      - selenium-chrome
    tty: true
    volumes:
      - flanco_scrape:/app/shared_dir
    environment:
      - SELENIUM_HOST=selenium-chrome
      - FLANCO_URL=https://www.flanco.ro/
    entrypoint: ["python3", "/app/flanco_scrape.py", "-v", "category", "telefoane-tablete/smartphone/smartphone-android.html"]
volumes:
  flanco_scrape: