version: "3.3"
services:
  selenium-chrome:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
  flanco:
    build: .
    depends_on:
      - selenium-chrome
    tty: true
    volumes:
      - flanco_scrape:/app/shared_dir
    environment:
      - SELENIUM_HOST=selenium-chrome
      - FLANCO_URL=https://www.flanco.ro/
    # entrypoint: ["python3", "/app/flanco_scrape.py", "-vv", "test"]
    # entrypoint: ["python3", "/app/flanco_scrape.py", "-v", "category", "tv-audio-video-foto/televizoare/smart-tv.html"]
    # entrypoint: ["python3", "/app/flanco_scrape.py", "-v", "category", "electrocasnice-mari/aparate-frigorifice/combine-frigorifice.html"]
    # entrypoint: ["python3", "/app/flanco_scrape.py", "-v", "-m", "100", "entire"]
    entrypoint: ["python3", "/app/flanco_scrape.py", "-v", "entire"]
volumes:
  flanco_scrape: