version: "3.3"
services:
  flanco:
    build: .
    depends_on:
      - selenium-chrome
    tty: true
    volumes:
      - flanco_scrape:/app/shared_dir
    environment:
      - SELENIUM_HOST=selenium-chrome
      - FLANCO_URL=https://www.flanco.ro/
  selenium-chrome:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
volumes:
  flanco_scrape: