version: "3.3"
services:
  flanco:
    build: .
    depends_on:
      - selenium-chrome
    volumes:
      - flanco_csv:/app/flanco_csv
    environment:
      - SELENIUM_HOST=selenium-chrome
      - FLANCO_URL=https://www.flanco.ro/

    # command: tail -F /dev/null
    tty: true
  selenium-chrome:
    image: "selenium/standalone-chrome"
    ports:
      - 4444:4444
volumes:
  flanco_csv: